### ISSUE TITLE
sign-up page

### ISSUE THREAD

**Issue by jharrisong830** [jharrisong830/cs546-group7#17]
sign up page should be linked to from the landing page, and should be a form that the user submits

we will need client side input validations on all fields (including birthdates and emails, see #12 and #13 for more details)

registerUser is already implemented, on successful submit we will call that

open to suggestions on methods of handling validation (jQuery seems to be the best option but idk!)

**Comment by jharrisong830** [comment]
currently using the signup route to test user creation, feel free to overwrite that route with any changes

**Comment by ehodor** [comment]
Will be using jQuery to handle client-side form validation

**Comment by jharrisong830** [comment]
use [this ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)for the date layout, update the `schema.md` to reflect new date format 

verify using the javascript builtin `Date`

**Comment by jharrisong830** [comment]
finished with #29
