### ISSUE TITLE
user profile page

### ISSUE THREAD

**Issue by jharrisong830** [jharrisong830/cs546-group7#23]
the `/user/<username>` route will display information about a user (we can use username in the route since all usernames will be unique, makes it more user-friendly and readable)

**on the current user's profile**, we show all data, and expose options for editing the profile and settings views

**for public profiles that are not the current user**, we'll display posts, comments, and other public info

**for private users that are not part of the current user's friend list**, show the username and an add friend option, but don't show posts

private users that are added as friends should have their profile shown as normal, perhaps with a little lock icon to indicate private (do this later, part of styling)

**Comment by ehodor** [comment]
added a lot to user profile page setup
 important note: I am currently distinguishing between the different profile views (viewing your own profile versus someone else) via if/unless segments in the handlebars instead of rendering different pages

**Comment by jharrisong830** [comment]
todo:

- hide settings when user viewed is not current user (check status of this)
- public users should have all posts shown (same as current user, just no settings)
- private users, don't show posts unless friended, in that case, link to request friend

**Comment by jharrisong830** [comment]
also: for current user, link to view friend requests
