### ISSUE TITLE
Username and password validation functions

### ISSUE THREAD

**Issue by jharrisong830** [jharrisong830/cs546-group7#25]
Should be synchronous functions, so that we can use the same functions client and server side

**Usernames**
- should allow all letters, numbers, and underscores (please use the `\w` regex character class to check for this, it already includes `[A-Za-z0-9_]`, and should already reject whitespace, other chars)
- after validated, it convert to lowercase and send to server (`registerUser` already handles checking for duplicates, converting and storing as all lowercase, etc. no need to worry about that in these funcs, but still would be good to convert to lowercase beforehand)
- length limit? I'd say at least 5 and no more than 25/30

**Passwords**
- case sensitive
- no whitespace allowed (the regex pattern should enforce this)
- perhaps use `\w` plus a few other special chars (i.e. `[\w*&%$#@!]`) (whatever is decided, **document it well and make sure the requirements are presented to the user**)
- **requirements**: 
1. at least 8 characters
2. one uppercase
3. one lowercase
4. one number
5. one special char

**Names**
- names are optional, if not provided, username will be main display name
- names should be more flexible (whitespace, all chars, emojis, etc.)
- length limit? I'd say cap at 30

**Comment by ehodor** [comment]
added all client-side sign up form validation checks in signup branch

**Comment by jharrisong830** [comment]
revised and finished in `public/js/signup_validation.js`

code can be pulled from there and used to make server-side functions
