### ISSUE TITLE
Middlewares

### ISSUE THREAD

**Issue by ehodor** [jharrisong830/cs546-group7#28]
We will need to add middleware functions (a la Lab 10) to reroute users depending on their current status (utilizing cookies).

 We should also decide what we will use to handle cookies (cookie-parser for client side cookies, express-session for server-side). I personally would like to use express-session

**Comment by jharrisong830** [comment]
imported express-session and added user data to `req.session.user` in `routes/signup.js`

merging main with #29 into Login+Middlewares branch

**Comment by jharrisong830** [comment]
Completed with #31
