### ISSUE TITLE
AJAX Form

### ISSUE THREAD

**Issue by ehodor** [jharrisong830/cs546-group7#32]
We will need to create a form that uses AJAX to transfer small data payloads and display them on current page user is on. 

In lecture, the professor suggested the login form is the simplest so he recommends that being the one to use AJAX. However, the login form is already done so we should decide on either re-doing that or converting another form to use AJAX.

**Comment by ehodor** [comment]
Update: John and I decided the AJAX form should be used for creating posts on the feed page. We are envisioning something similar to how Twitter on the Web works, with a tweet entry form at the top of the feed page.

**Comment by jharrisong830** [comment]
goes alongside #24
