### ISSUE TITLE
Ratings support

### ISSUE THREAD

**Issue by jharrisong830** [jharrisong830/cs546-group7#57]
in addition to comments, users can leave ratings on posts with playlists (same as comment, but with a rating of 1-5 stars)

we need to:
- make sure the ratings func from previous branch works
- render ratings properly, and also allow users to like a rating as they would a comment
- we can probably add the liking of comments in this branch too since it should be very similar
- maybe also refining the tags feature? allowing them to dismiss an unneeded tag field if they don't want to add one, etc.

**Comment by jharrisong830** [comment]
unlike comments, only one review should be submitted per user @RamsesPeralta7

**Comment by RamsesPeralta7** [comment]
fixed
