### ISSUE TITLE
Bugs and Comments/Likes on feed page (Finishing up!)

### ISSUE THREAD

**Issue by RamsesPeralta7** [jharrisong830/cs546-group7#58]
I recently made ratings branch and added likes to comments and made tags visible when clicking on a post that has a playlist. 
Right now we need to
- Fix bug where when you make a new post it takes time to actually show up (Might just be an issue with AJAX not sure)
- Fix bug where like button doesn't come up when you just make a comment (May be due to similar issues from above)
- Fix liking comments to work when there are multiple comments (Should be quick fix)
- Add comments and likes to show up on feed

I will probably be at these issues later today (friday) but if someone is able to handle something or if other bugs come up let me know.

**Comment by jharrisong830** [comment]
- [ ] Fix bug where when you make a new post it takes time to actually show up (Might just be an issue with AJAX not sure)
- [ ] Fix bug where like button doesn't come up when you just make a comment (May be due to similar issues from above)
- [ ] Fix liking comments to work when there are multiple comments (Should be quick fix)
- [ ] Add comments and likes to show up on feed

**Comment by jharrisong830** [comment]
first thing is an Ajax/browser issue. on safari the post actually stays on the feed after clicking it and moving back a page. on Firefox, it does not persist unless the feed is reloaded. not sure about chrome but its prolly similar

nothing to do for this issue

**Comment by jharrisong830** [comment]
like button not present at all on comments, will add this

also, what ordering do we want for comments? Ajax prepends a comment, but I believe they are returned in chronological order

**Comment by jharrisong830** [comment]
comment likes done on client side, database funcs need tweaking (can handle later)

**Comment by jharrisong830** [comment]
comments will not sort, not working at all lol
